# game settings
FPS = 60
TITLE = "PYDOOM"
WINDOW_HEIGHT = 900
WINDOW_WIDTH = 1600

# colors
BACKGROUND_COLOR = 'black'

# player
PLAYER_ANGLE = 0
PLAYER_POSITION = 1.5, 5
PLAYER_ROTATION_SPEED = 0.002
PLAYER_SPEED = 0.004
