# game settings
FPS = 60
TITLE = "PYDOOM"
WINDOW_HEIGHT = 900
WINDOW_WIDTH = 1600

# colors
FLOOR_COLOR = (30, 30, 30)

# player
PLAYER_ANGLE = 0
PLAYER_MAX_HEALTH = 100
PLAYER_POSITION = (2, 5)
PLAYER_SIZE_SCALE = 60
PLAYER_SPEED = 0.004

# ray casting
MAX_DEPTH = 20

# textures
TEXTURE_SIZE = 256

# mouse
MOUSE_BORDER_LEFT = 100
MOUSE_BORDER_RIGHT = WINDOW_WIDTH - MOUSE_BORDER_LEFT
MOUSE_MAX_RELATIVE_MOVEMENT = 40
MOUSE_SENSITIVITY = 0.0003
