from math import pi

# game settings
FPS = 60
TITLE = "PYDOOM"
WINDOW_HEIGHT = 900
WINDOW_WIDTH = 1600

# colors
BACKGROUND_COLOR = 'black'

# player
PLAYER_ANGLE = 0
PLAYER_POSITION = 1.5, 5
PLAYER_ROTATION_SPEED = 0.002
PLAYER_SPEED = 0.004

# ray casting
FIELD_OF_VISION = pi / 3
HALF_FIELD_OF_VISION = FIELD_OF_VISION / 2
NUM_RAYS = WINDOW_WIDTH // 2
HALF_NUM_RAYS = NUM_RAYS // 2
DELTA_ANGLE = FIELD_OF_VISION / NUM_RAYS
MAX_DEPTH = 20
